db:
  host: '192.168.0.101'
  port: 3306
  user: 'dev'
  password: 'password'
  name: 'match'

consumer:
  brokers: ['192.168.0.105:9092']
  topic: 'store.match.match'
  group_id: 'consumer-match-group'

cache:
  address: '192.168.0.105'
  port: ':6379'
  password: 'Awesome85**'
  db: 0
  pool_size: 25
  minimum_idle_connections: 10
  maximum_retries: 1
  match_key_format: 'match.%s.%s'
  token_key_format: 'token.%s'

firebase:
  function_address: 'https://us-central1-superheromatch.cloudfunctions.net/newMatch'
  content_type: 'application/json'

health:
  address: '192.168.0.101'
  port: ':8070'
  shutdown_endpoint: '/api/v1/consumer_superhero_match_health/shutdown'
  content_type: 'application/json'