db:
  host: 'localhost'
  port: 3306
  user: 'root'
  password: 'Kolian18**'
  name: 'match'

consumer:
  brokers: ['192.168.178.17:9092']
  topic: 'store.match.match'
  group_id: 'consumer-match-group'

cache:
  address: '192.168.178.17'
  port: ':6379'
  password: 'Awesome85**'
  db: 0
  pool_size: 25
  minimum_idle_connections: 10
  maximum_retries: 1
  match_key_format: 'match.%s.%s'

firebase:
  function_address: 'https://us-central1-superheromatch.cloudfunctions.net/newMatch'
  content_type: 'application/json'